/**
 * Default Dark — default production theme for symbiote-ui UI
 *
 * Cascadeable neutral shell aligned with the current Agent Portal theme.
 * Host applications can override the source controls at :root or a subtree.
 *
 * @module symbiote-ui/themes/default-dark
 */

import { themedScrollbarRootStyles } from './scrollbar-styles.js';

const DEFAULT_DARK_TOKENS = {
  '--sn-theme-variant': 'classic',
  '--sn-theme-hue': '218',
  '--sn-theme-chroma': '89%',
  '--sn-theme-bg-lightness': '10%',
  '--sn-theme-surface-lightness': '15.1%',
  '--sn-theme-text-lightness': '98.0%',
  '--sn-theme-density': '1',
  '--sn-theme-radius-scale': '0',
  '--sn-theme-tab-radius-scale': '1',
  '--sn-theme-cell-radius-scale': '1',
  '--sn-theme-composer-radius-scale': '1',
  '--sn-theme-pattern-brightness': '1.00',
  '--sn-theme-motion-scale': '1',
  '--sn-theme-elevation-scale': '1',

  '--sn-hue-base': '0',
  '--sn-hue-accent': 'var(--sn-theme-hue)',
  '--sn-hue-success': '122',
  '--sn-hue-warning': '36',
  '--sn-hue-danger': '4',
  '--sn-hue-data': '188',

  '--sn-sat': '0%',
  '--sn-sat-vivid': 'var(--sn-theme-chroma)',
  '--sn-sat-muted': '0%',

  '--sn-lit-bg': 'var(--sn-theme-bg-lightness)',
  '--sn-lit-surface': 'var(--sn-theme-surface-lightness)',
  '--sn-lit-hover': '31.2%',
  '--sn-lit-text': 'var(--sn-theme-text-lightness)',
  '--sn-lit-text-dim': '67.6%',
  '--sn-lit-accent': '68.0%',

  '--sn-alpha-overlay': '0.95',
  '--sn-alpha-subtle': '0.15',
  '--sn-alpha-faint': '0.06',
  '--sn-overlay-z-base': '20000',
  '--sn-canvas-overlay-z-base': '12000',
  '--sn-fullscreen-panel-z': '30010',
  '--sn-fullscreen-tab-bar-z': '30020',

  '--sn-sys-danger': 'hsl(var(--sn-hue-danger) var(--sn-sat-vivid) 58%)',
  '--sn-sys-success': 'hsl(var(--sn-hue-success) var(--sn-sat-vivid) 57%)',
  '--sn-sys-warning': 'hsl(var(--sn-hue-warning) var(--sn-sat-vivid) 58%)',
  '--sn-status-info': 'var(--sn-sys-accent)',
  '--sn-status-success': 'var(--sn-sys-success)',
  '--sn-status-warning': 'var(--sn-sys-warning)',
  '--sn-status-error': 'var(--sn-sys-danger)',
  '--sn-status-neutral': 'var(--sn-sys-on-surface-dim)',
  '--sn-status-info-bg': 'color-mix(in oklab, var(--sn-status-info) 14%, transparent)',
  '--sn-status-success-bg': 'color-mix(in oklab, var(--sn-status-success) 14%, transparent)',
  '--sn-status-warning-bg': 'color-mix(in oklab, var(--sn-status-warning) 14%, transparent)',
  '--sn-status-error-bg': 'color-mix(in oklab, var(--sn-status-error) 14%, transparent)',
  '--sn-status-neutral-bg': 'color-mix(in oklab, var(--sn-status-neutral) 10%, transparent)',
  '--sn-status-ok-bg': 'color-mix(in oklab, var(--sn-sys-success) 12%, transparent)',

  '--sn-sys-surface': 'hsl(0 0% var(--sn-lit-bg))',
  '--sn-sys-surface-panel': 'hsl(0 0% var(--sn-lit-surface))',
  '--sn-sys-surface-sunken': 'var(--sn-sys-surface)',
  '--sn-layout-gap-bg': 'transparent',
  '--sn-layout-border': 'transparent',
  '--sn-layout-resizer-bg': 'transparent',
  '--sn-layout-resizer-hover-bg': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.08)',
  '--sn-layout-resizer-size': '6px',
  '--sn-layout-header-min-height': 'calc(28px * var(--sn-theme-density))',
  '--sn-layout-header-button-size': 'calc(12px * var(--sn-theme-type-scale))',
  '--sn-layout-header-icon-size': 'calc(16px * var(--sn-theme-type-scale))',
  '--sn-layout-header-button-gap': 'calc(4px * var(--sn-theme-density))',
  '--sn-layout-header-button-padding': 'calc(4px * var(--sn-theme-density)) calc(6px * var(--sn-theme-density))',
  '--sn-layout-menu-min-height': 'calc(34px * var(--sn-theme-density))',
  '--sn-layout-menu-row-height': 'calc(30px * var(--sn-theme-density))',
  '--sn-layout-menu-padding': 'calc(3px * var(--sn-theme-density)) calc(6px * var(--sn-theme-density))',
  '--sn-layout-menu-row-padding': '0 calc(4px * var(--sn-theme-density))',
  '--sn-layout-menu-row-label-width': 'calc(66px * var(--sn-theme-density))',
  '--sn-layout-menu-label-padding': '0 calc(8px * var(--sn-theme-density))',
  '--sn-layout-menu-label-size': 'calc(11px * var(--sn-theme-type-scale))',
  '--sn-layout-menu-gap': 'calc(4px * var(--sn-theme-density))',
  '--sn-layout-menu-action-gap': 'calc(4px * var(--sn-theme-density))',
  '--sn-layout-menu-action-height': 'calc(28px * var(--sn-theme-density))',
  '--sn-layout-menu-action-padding': 'calc(4px * var(--sn-theme-density)) calc(8px * var(--sn-theme-density))',
  '--sn-layout-menu-action-size': 'calc(12px * var(--sn-theme-type-scale))',
  '--sn-layout-menu-icon-size': 'calc(16px * var(--sn-theme-type-scale))',
  '--sn-panel-menu-z': 'var(--sn-overlay-z-base)',
  '--sn-portal-bridge-z': '12',
  '--sn-portal-bridge-stroke': 'var(--sn-sys-accent)',
  '--sn-portal-bridge-width': '2',
  '--sn-portal-bridge-dash': '7 7',
  '--sn-portal-bridge-dot': 'var(--sn-sys-accent)',
  '--sn-portal-bridge-grid': '20',
  '--sn-portal-bridge-stub': '36',
  '--sn-portal-bridge-clearance': '28',
  '--sn-portal-bridge-chamfer': '8',
  '--sn-xr-panel-bg': 'var(--sn-sys-surface-panel)',
  '--sn-xr-panel-border': 'var(--sn-sys-outline)',
  '--sn-xr-panel-radius': 'var(--sn-node-radius)',
  '--sn-xr-panel-shadow': 'var(--sn-node-shadow)',
  '--sn-xr-pointer-color': 'var(--sn-sys-accent)',
  '--sn-bg-overlay': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) 0% / 0.45)',
  '--sn-grid-dot': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.088)',
  '--sn-grid-size': '20px',
  '--sn-cell-bg': 'var(--sn-sys-surface)',
  '--sn-cell-dot': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) 31%)',
  '--sn-cell-base-alpha': '0.047',
  '--sn-cell-alpha-span': '0.175',
  '--sn-chat-cell-base-alpha': '0.012',
  '--sn-chat-cell-alpha-span': '0.070',
  '--sn-cell-glare': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.019)',
  '--sn-cell-vignette-mid': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-bg) / 0.7)',
  '--sn-cell-vignette-edge': 'var(--sn-sys-surface)',
  '--sn-cell-noise': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 256 256\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'n\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'1.5\' numOctaves=\'2\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23n)\' opacity=\'0.030\'/%3E%3C/svg%3E")',
  '--sn-cell-min-radius': 'calc(2px * var(--sn-theme-cell-radius-scale, 1))',
  '--sn-cell-max-radius': 'calc(5px * var(--sn-theme-cell-radius-scale, 1))',

  '--sn-sys-surface-raised': 'var(--sn-sys-surface-panel)',
  '--sn-sys-outline': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.1)',
  '--sn-border': 'var(--sn-sys-outline)',
  '--sn-node-min-width': '180px',
  '--sn-node-max-width': '280px',
  '--sn-node-border-width': '2px',
  '--sn-node-font-size': '13px',
  '--sn-node-items-max-height': '420px',
  '--sn-node-callout-z': 'var(--sn-canvas-overlay-z-base)',
  '--sn-node-callout-bg': 'color-mix(in oklab, var(--sn-sys-surface-raised) 94%, var(--sn-sys-accent) 6%)',
  '--sn-node-callout-border': 'color-mix(in oklab, var(--sn-sys-accent) 28%, var(--sn-sys-outline))',
  '--sn-node-callout-color': 'var(--sn-sys-on-surface)',
  '--sn-node-callout-shadow': 'var(--sn-shadow-lg)',
  '--sn-node-callout-radius': 'calc(8px * var(--sn-theme-radius-scale))',
  '--sn-node-callout-padding': '10px 12px',
  '--sn-node-callout-max-width': '520px',
  '--sn-node-callout-offset': '14px',
  '--sn-node-callout-font-size': '12px',
  '--sn-node-callout-font-weight': '700',
  '--sn-node-callout-line-height': '1.35',
  '--sn-node-callout-arrow-size': '10px',
  '--sn-node-error-frame-offset': '10px',
  '--sn-node-error-frame-min-width': '140px',
  '--sn-node-error-frame-max-width': '320px',
  '--sn-node-error-frame-border-width': '2px',
  '--sn-node-error-frame-radius': 'calc(12px * var(--sn-theme-radius-scale))',
  '--sn-node-radius': 'calc(6px * var(--sn-theme-radius-scale))',
  '--sn-node-shadow': '0 2px calc(8px * var(--sn-theme-elevation-scale)) hsl(var(--sn-hue-base) var(--sn-sat-muted) 0% / 0.4)',
  '--sn-node-active-border': 'color-mix(in oklab, var(--sn-sys-accent) 50%, transparent)',
  '--sn-shadow-color': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) 0% / 0.4)',
  '--sn-shadow-sm': '0 1px calc(4px * var(--sn-theme-elevation-scale)) hsl(var(--sn-hue-base) var(--sn-sat-muted) 0% / 0.22)',
  '--sn-shadow-md': '0 2px calc(8px * var(--sn-theme-elevation-scale)) hsl(var(--sn-hue-base) var(--sn-sat-muted) 0% / 0.28)',
  '--sn-shadow-lg': '0 6px calc(18px * var(--sn-theme-elevation-scale)) hsl(var(--sn-hue-base) var(--sn-sat-muted) 0% / 0.28)',
  '--sn-shadow-xl': '0 -8px calc(28px * var(--sn-theme-elevation-scale)) hsl(var(--sn-hue-base) var(--sn-sat-muted) 0% / 0.32)',
  '--sn-panel-radius': 'var(--sn-node-radius)',
  '--sn-panel-shadow': 'var(--sn-shadow-md)',
  '--sn-layout-drawer-shadow': 'var(--sn-shadow-xl)',
  '--sn-node-header-bg': 'var(--sn-sys-surface-panel)',
  '--sn-sys-accent': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent))',
  '--sn-node-accent': 'var(--sn-sys-accent)',

  '--sn-font': "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  '--sn-font-mono': "'JetBrains Mono', 'Fira Code', monospace",
  '--sn-font-ui': "var(--sn-font)",
  '--sn-font-family': "var(--sn-font)",
  '--sn-icon-font': "'Material Symbols Outlined'",
  '--sn-sys-on-surface': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text))',
  '--sn-sys-on-surface-dim': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text-dim))',

  '--sn-socket-size': '12px',
  '--sn-socket-border-width': '2px',

  '--sn-conn-color': 'var(--sn-sys-accent)',
  '--sn-conn-width': '2',
  '--sn-conn-selected': 'hsl(var(--sn-hue-danger) var(--sn-sat-vivid) 58%)',
  '--sn-conn-linecap': 'round',
  '--sn-conn-linejoin': 'round',
  '--sn-conn-dot-fill': 'var(--sn-conn-color)',
  '--sn-conn-dot-stroke': 'var(--sn-sys-surface-raised)',
  '--sn-conn-dot-stroke-width': 'var(--sn-socket-border-width)',
  '--sn-conn-dot-r': 'calc((var(--sn-socket-size) + var(--sn-conn-dot-stroke-width)) / 2)',
  '--sn-graph-explorer-overlay-z': '100',
  '--sn-graph-explorer-toolbar-top': '8px',
  '--sn-graph-explorer-toolbar-right': '8px',
  '--sn-graph-explorer-toolbar-gap': '6px',
  '--sn-graph-explorer-toolbar-z': '200',
  '--sn-graph-explorer-stats-bottom': '8px',
  '--sn-graph-explorer-stats-left': '8px',
  '--sn-graph-explorer-stats-z': '10',
  '--sn-graph-type-action': 'var(--sn-type-action)',
  '--sn-graph-type-output': 'var(--sn-type-output)',
  '--sn-graph-type-data': 'var(--sn-type-data)',
  '--sn-graph-type-config': 'var(--sn-type-config)',
  '--sn-graph-type-external': 'var(--sn-type-external)',
  '--sn-graph-type-style': 'var(--sn-type-style)',
  '--sn-graph-type-docs': 'var(--sn-type-docs)',
  '--sn-graph-type-asset': 'var(--sn-type-asset)',
  '--sn-graph-type-group': 'var(--sn-type-group)',
  '--sn-graph-type-directory': 'var(--sn-type-directory)',
  '--sn-graph-type-file': 'var(--sn-type-file)',
  '--sn-graph-type-source': 'var(--sn-type-source)',
  '--sn-graph-type-canvas': 'var(--sn-type-canvas)',
  '--sn-graph-type-layout': 'var(--sn-type-layout)',
  '--sn-graph-type-controls': 'var(--sn-type-controls)',
  '--sn-graph-type-control': 'var(--sn-type-control)',
  '--sn-graph-type-profile': 'var(--sn-type-profile)',
  '--sn-graph-type-profile-photo': 'var(--sn-type-profile-photo)',
  '--sn-graph-type-bio': 'var(--sn-type-bio)',
  '--sn-graph-type-portal': 'var(--sn-type-portal)',
  '--sn-graph-type-project': 'var(--sn-type-project)',
  '--sn-graph-type-pulse': 'var(--sn-type-pulse)',
  '--sn-graph-type-skill': 'var(--sn-type-skill)',
  '--sn-graph-type-function': 'var(--sn-type-function)',
  '--sn-graph-type-class': 'var(--sn-type-class)',
  '--sn-graph-type-module': 'var(--sn-type-module)',
  '--sn-canvas-graph-bg': 'var(--sn-sys-surface)',
  '--sn-canvas-graph-edge': 'var(--sn-conn-color)',
  '--sn-canvas-graph-pulse': 'var(--sn-sys-accent)',
  '--sn-canvas-graph-danger': 'var(--sn-sys-danger)',
  '--sn-canvas-graph-text': 'var(--sn-sys-on-surface)',
  '--sn-canvas-graph-text-dim': 'var(--sn-sys-on-surface-dim)',
  '--sn-canvas-graph-panel-bg': 'var(--sn-canvas-graph-bg)',
  '--sn-canvas-graph-panel-border': 'var(--sn-sys-outline)',
  '--sn-canvas-graph-ghost': 'var(--sn-sys-on-surface-dim)',
  '--sn-canvas-graph-radial-icon': 'var(--sn-sys-surface)',
  '--sn-graph-cluster-0': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) 74%)',
  '--sn-graph-cluster-1': 'hsl(var(--sn-hue-success) var(--sn-sat-vivid) 66%)',
  '--sn-graph-cluster-2': 'hsl(var(--sn-hue-warning) var(--sn-sat-vivid) 68%)',
  '--sn-graph-cluster-3': 'hsl(var(--sn-hue-danger) var(--sn-sat-vivid) 74%)',
  '--sn-graph-cluster-4': 'hsl(var(--sn-hue-data) var(--sn-sat-vivid) 76%)',
  '--sn-graph-cluster-5': 'hsl(calc(var(--sn-hue-accent) - 40) var(--sn-sat-vivid) 72%)',
  '--sn-graph-cluster-6': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) 82%)',
  '--sn-minimap-bg': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-bg) / 0.85)',
  '--sn-minimap-node': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.6)',
  '--sn-minimap-node-stroke': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.3)',
  '--sn-minimap-bypassed-node': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text-dim) / 0.5)',
  '--sn-minimap-viewport': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.6)',
  '--sn-minimap-viewport-fill': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.04)',
  '--sn-dot-output': 'hsl(var(--sn-hue-warning) var(--sn-sat-vivid) 63%)',
  '--sn-dot-input': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) 63%)',
  '--sn-dot-exec': 'hsl(var(--sn-hue-warning) var(--sn-sat-vivid) 64%)',
  '--sn-dot-ctrl': 'var(--sn-sys-success)',

  '--sn-cat-server': 'var(--sn-sys-accent)',
  '--sn-cat-instance': 'hsl(var(--sn-hue-success) var(--sn-sat-vivid) 57%)',
  '--sn-cat-control': 'hsl(var(--sn-hue-warning) var(--sn-sat-vivid) 58%)',
  '--sn-cat-data': 'hsl(var(--sn-hue-data) var(--sn-sat-vivid) 47.0%)',
  '--sn-cat-default': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) 40%)',
  '--sn-cat-directory': 'hsl(var(--sn-hue-warning) var(--sn-sat-vivid) 60%)',
  '--sn-cat-file': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) 66%)',
  '--sn-cat-function': 'var(--sn-sys-success)',
  '--sn-cat-class': 'hsl(var(--sn-hue-data) var(--sn-sat-vivid) 72%)',
  '--sn-cat-module': 'hsl(var(--sn-hue-danger) var(--sn-sat-vivid) 70%)',
  '--sn-type-default': 'var(--sn-node-category-accent)',
  '--sn-type-action': 'hsl(var(--sn-hue-danger) var(--sn-sat-vivid) 82.0%)',
  '--sn-type-output': 'hsl(var(--sn-hue-success) var(--sn-sat-vivid) 65%)',
  '--sn-type-data': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) 79.0%)',
  '--sn-type-config': 'hsl(var(--sn-hue-warning) var(--sn-sat-vivid) 68%)',
  '--sn-type-external': 'hsl(var(--sn-hue-data) var(--sn-sat-vivid) 76%)',
  '--sn-type-style': 'hsl(calc(var(--sn-hue-danger) + 315) var(--sn-sat-vivid) 78%)',
  '--sn-type-docs': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) 85.0%)',
  '--sn-type-asset': 'hsl(calc(var(--sn-hue-accent) - 40) var(--sn-sat-vivid) 74%)',
  '--sn-type-group': 'hsl(calc(var(--sn-hue-warning) + 8) var(--sn-sat-vivid) 67%)',
  '--sn-type-directory': 'var(--sn-cat-directory)',
  '--sn-type-file': 'var(--sn-cat-file)',
  '--sn-type-function': 'var(--sn-cat-function)',
  '--sn-type-class': 'var(--sn-cat-class)',
  '--sn-type-module': 'var(--sn-cat-module)',
  '--sn-type-control': 'var(--sn-cat-control)',
  '--sn-type-controls': 'var(--sn-cat-control)',
  '--sn-type-source': 'var(--sn-cat-server)',
  '--sn-type-canvas': 'var(--sn-cat-module)',
  '--sn-type-layout': 'var(--sn-cat-data)',
  '--sn-type-profile': 'hsl(var(--sn-hue-data) var(--sn-sat-vivid) 58%)',
  '--sn-type-profile-photo': 'var(--sn-type-profile)',
  '--sn-type-profile-info': 'var(--sn-sys-success)',
  '--sn-type-bio': 'var(--sn-type-profile-info)',
  '--sn-type-portal': 'var(--sn-cat-control)',
  '--sn-type-project': 'hsl(24 var(--sn-sat-vivid) 62%)',
  '--sn-type-pulse': 'var(--sn-type-docs)',
  '--sn-type-skill': 'var(--sn-cat-control)',
  '--sn-accent-warn': 'var(--sn-sys-warning)',
  '--sn-message-event-bg': 'color-mix(in oklab, var(--sn-cat-server) 10%, transparent)',
  '--sn-subgraph-accent': 'var(--sn-cat-data)',
  '--sn-subgraph-bg': 'linear-gradient(135deg, color-mix(in oklab, var(--sn-subgraph-accent) 12%, transparent) 0%, color-mix(in oklab, var(--sn-subgraph-accent) 8%, transparent) 100%)',
  '--sn-subgraph-bg-hover': 'linear-gradient(135deg, color-mix(in oklab, var(--sn-subgraph-accent) 22%, transparent) 0%, color-mix(in oklab, var(--sn-subgraph-accent) 15%, transparent) 100%)',
  '--sn-subgraph-border': 'color-mix(in oklab, var(--sn-subgraph-accent) 30%, transparent)',
  '--sn-subgraph-border-hover': 'color-mix(in oklab, var(--sn-subgraph-accent) 50%, transparent)',
  '--sn-subgraph-preview-connection': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.12)',
  '--sn-subgraph-preview-completed-connection': 'hsl(var(--sn-hue-success) var(--sn-sat-vivid) 57% / 0.5)',
  '--sn-subgraph-preview-processing-fill': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.25)',
  '--sn-subgraph-preview-processing-stroke': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.8)',
  '--sn-subgraph-preview-processing-glow': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.6)',
  '--sn-subgraph-preview-completed-fill': 'hsl(var(--sn-hue-success) var(--sn-sat-vivid) 57% / 0.2)',
  '--sn-subgraph-preview-completed-stroke': 'hsl(var(--sn-hue-success) var(--sn-sat-vivid) 57% / 0.7)',
  '--sn-subgraph-preview-idle-fill': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.08)',
  '--sn-subgraph-preview-idle-stroke': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.2)',

  '--sn-provider-rnd-pro-color': 'var(--sn-cat-data)',
  '--sn-provider-rnd-pro-bg': 'color-mix(in oklab, var(--sn-provider-rnd-pro-color) 20%, transparent)',
  '--sn-provider-official-color': 'var(--sn-sys-accent)',
  '--sn-provider-official-bg': 'color-mix(in oklab, var(--sn-provider-official-color) 20%, transparent)',
  '--sn-provider-google-color': 'var(--sn-sys-success)',
  '--sn-provider-google-bg': 'color-mix(in oklab, var(--sn-provider-google-color) 20%, transparent)',
  '--sn-provider-community-color': 'var(--sn-sys-warning)',
  '--sn-provider-community-bg': 'color-mix(in oklab, var(--sn-provider-community-color) 20%, transparent)',
  '--sn-provider-default-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-provider-default-bg': 'color-mix(in oklab, var(--sn-provider-default-color) 20%, transparent)',

  '--sn-sys-surface-overlay': 'color-mix(in oklab, var(--sn-sys-surface-panel) 82%, var(--sn-sys-on-surface) 4%)',
  '--sn-ctx-border': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.1)',
  '--sn-ctx-color': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text))',
  '--sn-ctx-hover': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.15)',
  '--sn-ctx-z': 'var(--sn-canvas-overlay-z-base)',

  '--sn-accent-bg': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.12)',
  '--sn-accent-bg-subtle': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.06)',
  '--sn-accent-border': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.2)',
  '--sn-accent-glow': '0 0 12px hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.12)',
  '--sn-success-bg': 'color-mix(in oklab, var(--sn-sys-success) 18%, transparent)',
  '--sn-success-bg-hover': 'color-mix(in oklab, var(--sn-sys-success) 28%, transparent)',
  '--sn-success-border-hover': 'color-mix(in oklab, var(--sn-sys-success) 52%, transparent)',
  '--sn-danger-bg': 'color-mix(in oklab, var(--sn-sys-danger) 18%, transparent)',

  '--sn-comment-bg': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.04)',
  '--sn-comment-border': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.08)',
  '--sn-comment-radius': '4px',

  '--sn-toolbar-bg': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-surface) / 0.95)',
  '--sn-toolbar-border': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.08)',
  '--sn-toolbar-color': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text-dim))',
  '--sn-toolbar-hover': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.18)',
  '--sn-toolbar-occlusion-bg': 'var(--sn-sys-surface-panel)',
  '--sn-toolbar-active': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text))',
  '--sn-toolbar-danger': 'hsl(var(--sn-hue-danger) var(--sn-sat-vivid) 58% / 0.22)',
  '--sn-toolbar-danger-color': 'hsl(var(--sn-hue-danger) var(--sn-sat-vivid) 58%)',
  '--sn-toolbar-z': 'var(--sn-canvas-overlay-z-base)',
  '--sn-toolbar-title-color': 'var(--sn-sys-on-surface)',
  '--sn-toolbar-title-font-size': '12px',
  '--sn-toolbar-title-font-weight': '700',
  '--sn-toolbar-title-line-height': '1.35',
  '--sn-toolbar-title-min-width': '220px',
  '--sn-toolbar-title-max-width': 'clamp(300px, 48vw, 420px)',
  '--sn-toolbar-title-lines': '2',

  '--sn-scrollbar-thumb': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.08)',
  '--sn-scrollbar-thumb-hover': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.25)',
  '--sn-scrollbar-track': 'transparent',
  '--sn-scrollbar-width': 'thin',
  '--sn-scrollbar-size': '10px',
  '--sn-scrollbar-radius': '999px',
  '--sn-scrollbar-thumb-border': '3px solid transparent',
  '--sn-scrollbar-thumb-min-size': '36px',
  '--sn-scroll-shadow-size': '14px',

  '--sn-tabs-height': '38px',
  '--sn-tabs-item-height': '32px',
  '--sn-tabs-bg': 'transparent',
  '--sn-tabs-shape': 'classic-ear',
  '--sn-tabs-border': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.08)',
  '--sn-tabs-active-bg': 'var(--sn-sys-surface-raised)',
  '--sn-tabs-active-color': 'var(--sn-sys-on-surface)',
  '--sn-tabs-active-border': 'transparent',
  '--sn-tabs-hover-bg': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.04)',
  '--sn-tabs-divider': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.1)',
  '--sn-tabs-accent': 'var(--sn-sys-accent)',
  '--sn-tab-accent-0': 'var(--sn-cat-server)',
  '--sn-tab-accent-1': 'var(--sn-cat-data)',
  '--sn-tab-accent-2': 'var(--sn-cat-control)',
  '--sn-tab-accent-3': 'var(--sn-cat-instance)',
  '--sn-tab-accent-4': 'var(--sn-type-action)',
  '--sn-tab-accent-5': 'var(--sn-cat-class)',
  '--sn-tabs-corner-radius': 'calc(8px * var(--sn-theme-density, 1) * var(--sn-theme-tab-radius-scale, 1))',
  '--sn-tabs-radius': 'var(--sn-tabs-corner-radius)',
  '--sn-tabs-corner-size': '12px',
  '--sn-tabs-corner-cut': '11.5px',

  '--sn-tree-gap': '4px',
  '--sn-tree-indent': '16px',
  '--sn-tree-toggle-width': '18px',
  '--sn-tree-icon-width': '18px',
  '--sn-tree-row-height': 'calc(22px * var(--sn-theme-density))',
  '--sn-tree-row-min-height': 'calc(22px * var(--sn-theme-density))',
  '--sn-tree-row-padding-block': '2px',
  '--sn-tree-row-radius': 'calc(4px * var(--sn-theme-radius-scale))',
  '--sn-tree-row-hover-bg': 'color-mix(in oklch, var(--sn-sys-accent) var(--sn-sys-state-hover-mix), var(--sn-sys-surface-panel))',
  '--sn-tree-row-selected-bg': 'var(--sn-accent-bg-subtle)',
  '--sn-tree-row-selected-border': 'transparent',
  '--sn-tree-row-focus-border': 'var(--sn-sys-accent)',
  '--sn-tree-label-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-tree-label-size': '12px',
  '--sn-tree-label-weight': '500',
  '--sn-tree-muted-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-tree-icon-size': '15px',
  '--sn-tree-badge-radius': '8px',
  '--sn-tree-badge-bg': 'var(--sn-sys-accent-container)',
  '--sn-tree-badge-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-tree-badge-size': '10px',
  '--sn-tree-badge-max-width': '88px',
  '--sn-tree-kind-size': '10px',
  '--sn-tree-kind-max-width': '120px',
  '--sn-tree-panel-font-size': '12px',
  '--sn-tree-panel-title-gap': '5px',
  '--sn-tree-panel-title-padding': '6px 8px',
  '--sn-tree-panel-title-size': '11px',
  '--sn-tree-panel-title-weight': '700',
  '--sn-tree-panel-icon-size': '14px',
  '--sn-tree-panel-toolbar-gap': '6px',
  '--sn-tree-panel-toolbar-padding': '6px 8px',
  '--sn-tree-panel-input-padding': '4px 8px',
  '--sn-tree-panel-input-radius': 'calc(4px * var(--sn-theme-radius-scale))',
  '--sn-tree-panel-input-size': '11px',
  '--sn-tree-panel-collapse-padding': '0 6px',
  '--sn-tree-panel-content-padding': '4px',
  '--sn-tree-panel-placeholder-padding': '8px',
  '--sn-tree-panel-placeholder-size': '12px',
  '--sn-tree-panel-row-min-height': 'var(--sn-tree-row-min-height)',
  '--sn-tree-panel-label-weight': 'var(--sn-tree-label-weight)',
  '--sn-card-bg': 'var(--sn-sys-surface-raised)',
  '--sn-card-border': 'var(--sn-sys-outline)',
  '--sn-card-radius': 'var(--sn-node-radius)',
  '--sn-card-padding': '14px',
  '--sn-card-margin-block-end': '12px',
  '--sn-card-hover-bg': 'color-mix(in oklch, var(--sn-sys-accent) var(--sn-sys-state-hover-mix), var(--sn-card-bg))',
  '--sn-card-hover-border': 'var(--sn-sys-accent)',
  '--sn-card-title-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-card-title-size': '11px',
  '--sn-card-title-weight': '600',
  '--sn-card-title-margin-block-end': '12px',
  '--sn-card-footer-gap': '8px',
  '--sn-card-footer-margin-block-start': '16px',
  '--sn-card-footer-padding-block-start': '16px',
  '--sn-dialog-bg': 'var(--sn-sys-surface-panel)',
  '--sn-dialog-color': 'var(--sn-sys-on-surface)',
  '--sn-dialog-border': 'var(--sn-sys-outline)',
  '--sn-dialog-border-width': '1px',
  '--sn-dialog-radius': 'calc(8px * var(--sn-theme-radius-scale))',
  '--sn-dialog-shadow': 'var(--sn-shadow-lg)',
  '--sn-dialog-backdrop': 'var(--sn-bg-overlay)',
  '--sn-dialog-body-padding': 'calc(20px * var(--sn-theme-density))',
  '--sn-dialog-font-size': '14px',
  '--sn-dialog-min-width': '250px',
  '--sn-dialog-message-gap': 'calc(20px * var(--sn-theme-density))',
  '--sn-dialog-prompt-message-gap': 'calc(10px * var(--sn-theme-density))',
  '--sn-dialog-actions-gap': 'calc(10px * var(--sn-theme-density))',
  '--sn-dialog-actions-margin-block-start': 'calc(20px * var(--sn-theme-density))',
  '--sn-button-bg': 'var(--sn-sys-surface-raised)',
  '--sn-button-color': 'var(--sn-sys-on-surface)',
  '--sn-button-border': 'var(--sn-sys-outline)',
  '--sn-button-padding': '6px 14px',
  '--sn-button-radius': 'calc(8px * var(--sn-theme-radius-scale))',
  '--sn-button-gap': '6px',
  '--sn-button-min-height': '30px',
  '--sn-button-font-size': '12px',
  '--sn-button-font-weight': '500',
  '--sn-button-line-height': '1.2',
  '--sn-button-hover-bg': 'var(--sn-sys-surface-raised)',
  '--sn-button-hover-border': 'var(--sn-sys-accent)',
  '--sn-button-disabled-opacity': '0.5',
  '--sn-button-primary-bg': 'var(--sn-sys-accent)',
  '--sn-button-primary-border': 'var(--sn-sys-accent)',
  '--sn-button-primary-color': 'var(--sn-sys-on-surface)',
  '--sn-button-primary-hover-filter': 'brightness(1.1)',
  '--sn-button-success-bg': 'var(--sn-sys-success)',
  '--sn-button-success-border': 'var(--sn-sys-success)',
  '--sn-button-success-color': 'var(--sn-sys-surface)',
  '--sn-button-success-hover-bg': 'color-mix(in oklab, var(--sn-sys-success) 85%, var(--sn-sys-on-surface))',
  '--sn-button-success-hover-border': 'color-mix(in oklab, var(--sn-sys-success) 85%, var(--sn-sys-on-surface))',
  '--sn-button-success-hover-color': 'var(--sn-sys-surface)',
  '--sn-button-danger-bg': 'transparent',
  '--sn-button-danger-border': 'var(--sn-sys-danger)',
  '--sn-button-danger-color': 'var(--sn-sys-danger)',
  '--sn-button-danger-hover-bg': 'var(--sn-sys-danger)',
  '--sn-button-danger-hover-border': 'var(--sn-sys-danger)',
  '--sn-button-danger-hover-color': 'var(--sn-sys-on-surface)',
  '--sn-button-icon-size': '28px',
  '--sn-button-icon-font-size': '16px',
  '--sn-button-focus-ring': 'var(--sn-effect-focus-ring)',
  '--sn-field-margin-block-end': '12px',
  '--sn-field-label-margin-block-end': '4px',
  '--sn-field-label-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-field-label-size': '11px',
  '--sn-field-label-weight': '500',
  '--sn-field-label-line-height': '1.2',
  '--sn-field-label-transform': 'uppercase',
  '--sn-field-control-bg': 'var(--sn-sys-surface)',
  '--sn-field-control-border': 'var(--sn-sys-outline)',
  '--sn-field-control-color': 'var(--sn-sys-on-surface)',
  '--sn-field-control-padding': '8px 12px',
  '--sn-field-control-radius': 'calc(6px * var(--sn-theme-radius-scale))',
  '--sn-field-control-font-size': '12px',
  '--sn-field-control-line-height': '1.4',
  '--sn-field-control-focus-border': 'var(--sn-sys-accent)',
  '--sn-field-control-focus-shadow': 'none',
  '--sn-field-control-subtle-border': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / var(--sn-alpha-faint))',
  '--sn-field-placeholder-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-field-textarea-min-height': '120px',
  '--sn-field-hint-margin-block-start': '4px',
  '--sn-field-hint-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-field-hint-size': '11px',
  '--sn-field-hint-line-height': '1.4',
  '--sn-field-inline-gap': '8px',
  '--sn-field-compact-margin-block-end': '8px',
  '--sn-field-compact-control-padding': '6px 10px',
  '--sn-field-select-indicator': 'linear-gradient(45deg, transparent 50%, var(--sn-sys-on-surface-dim) 50%), linear-gradient(135deg, var(--sn-sys-on-surface-dim) 50%, transparent 50%)',
  '--sn-field-toggle-bg': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.1)',
  '--sn-field-toggle-thumb-bg': 'var(--sn-sys-on-surface-dim)',
  '--sn-field-toggle-thumb-active-bg': 'var(--sn-sys-on-surface)',
  '--sn-badge-bg': 'var(--sn-sys-surface-raised)',
  '--sn-badge-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-badge-border': 'var(--sn-sys-outline)',
  '--sn-badge-padding': '2px 8px',
  '--sn-badge-radius': 'calc(12px * var(--sn-theme-radius-scale))',
  '--sn-badge-gap': '4px',
  '--sn-badge-font-size': '12px',
  '--sn-badge-font-weight': '500',
  '--sn-badge-line-height': '1.2',
  '--sn-badge-success-bg': 'var(--sn-status-success-bg)',
  '--sn-badge-success-color': 'var(--sn-sys-success)',
  '--sn-badge-success-border': 'var(--sn-sys-success)',
  '--sn-badge-info-bg': 'var(--sn-status-info-bg)',
  '--sn-badge-info-color': 'var(--sn-sys-accent)',
  '--sn-badge-info-border': 'var(--sn-sys-accent)',
  '--sn-badge-warning-bg': 'var(--sn-status-warning-bg)',
  '--sn-badge-warning-color': 'var(--sn-sys-warning)',
  '--sn-badge-warning-border': 'var(--sn-sys-warning)',
  '--sn-badge-error-bg': 'var(--sn-status-error-bg)',
  '--sn-badge-error-color': 'var(--sn-sys-danger)',
  '--sn-badge-error-border': 'var(--sn-sys-danger)',
  '--sn-badge-neutral-bg': 'var(--sn-status-neutral-bg)',
  '--sn-badge-neutral-color': 'var(--sn-status-neutral)',
  '--sn-badge-neutral-border': 'var(--sn-sys-outline)',
  '--sn-banner-bg': 'var(--sn-sys-surface-raised)',
  '--sn-banner-color': 'var(--sn-sys-on-surface)',
  '--sn-banner-border': 'var(--sn-sys-outline)',
  '--sn-banner-padding': '10px 14px',
  '--sn-banner-radius': 'calc(8px * var(--sn-theme-radius-scale))',
  '--sn-banner-gap': '8px',
  '--sn-banner-margin-block-end': '16px',
  '--sn-banner-font-size': '12px',
  '--sn-banner-font-weight': '500',
  '--sn-banner-line-height': '1.4',
  '--sn-banner-icon-size': '18px',
  '--sn-banner-info-bg': 'var(--sn-status-info-bg)',
  '--sn-banner-info-color': 'var(--sn-sys-accent)',
  '--sn-banner-info-border': 'var(--sn-sys-accent)',
  '--sn-banner-success-bg': 'var(--sn-status-success-bg)',
  '--sn-banner-success-color': 'var(--sn-sys-success)',
  '--sn-banner-success-border': 'var(--sn-sys-success)',
  '--sn-banner-warning-bg': 'var(--sn-status-warning-bg)',
  '--sn-banner-warning-color': 'var(--sn-sys-warning)',
  '--sn-banner-warning-border': 'var(--sn-sys-warning)',
  '--sn-banner-error-bg': 'var(--sn-status-error-bg)',
  '--sn-banner-error-color': 'var(--sn-sys-danger)',
  '--sn-banner-error-border': 'var(--sn-sys-danger)',
  '--sn-banner-running-spin-duration': '2s',
  '--sn-empty-state-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-empty-state-error-color': 'var(--sn-sys-danger)',
  '--sn-empty-state-padding': '20px',
  '--sn-empty-state-gap': '8px',
  '--sn-empty-state-min-height': '0',
  '--sn-empty-state-height': '100%',
  '--sn-empty-state-font-size': '13px',
  '--sn-empty-state-font-style': 'italic',
  '--sn-empty-state-line-height': '1.4',
  '--sn-empty-state-icon-size': '18px',
  '--sn-metric-gap': '12px',
  '--sn-metric-padding': '5px 0',
  '--sn-metric-border': 'var(--sn-sys-outline-subtle)',
  '--sn-metric-color': 'var(--sn-sys-on-surface)',
  '--sn-metric-label-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-metric-label-size': '12px',
  '--sn-metric-value-color': 'var(--sn-sys-on-surface)',
  '--sn-metric-value-size': '12px',
  '--sn-metric-value-weight': '600',
  '--sn-metric-value-font': 'var(--sn-font-mono)',
  '--sn-metric-success-color': 'var(--sn-sys-success)',
  '--sn-metric-warning-color': 'var(--sn-sys-warning)',
  '--sn-metric-error-color': 'var(--sn-sys-danger)',
  '--sn-data-table-bg': 'var(--sn-sys-surface-raised)',
  '--sn-data-table-border': 'var(--sn-sys-outline)',
  '--sn-data-table-radius': 'calc(8px * var(--sn-theme-radius-scale))',
  '--sn-data-table-color': 'var(--sn-sys-on-surface)',
  '--sn-data-table-header-bg': 'var(--sn-sys-surface-panel)',
  '--sn-data-table-header-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-data-table-header-border': 'var(--sn-sys-outline)',
  '--sn-data-table-header-size': '11px',
  '--sn-data-table-header-weight': '500',
  '--sn-data-table-header-transform': 'uppercase',
  '--sn-data-table-row-border': 'var(--sn-sys-outline-subtle)',
  '--sn-data-table-cell-padding': '12px 15px',
  '--sn-data-table-cell-size': '13px',
  '--sn-data-table-cell-gap': '10px',
  '--sn-data-table-line-height': '1.4',
  '--sn-data-table-min-width': '0',
  '--sn-data-table-marker-size': '12px',
  '--sn-data-table-marker-radius': '50%',
  '--sn-data-table-empty-padding': '12px 15px',
  '--sn-data-table-empty-color': 'var(--sn-sys-on-surface-dim)',

  '--sn-list-item-bg': 'transparent',
  '--sn-list-item-hover-bg': 'color-mix(in oklch, var(--sn-sys-accent) var(--sn-sys-state-hover-mix), var(--sn-sys-surface-raised))',
  '--sn-list-item-active-bg': 'var(--sn-accent-bg-subtle)',
  '--sn-list-item-active-border': 'var(--sn-sys-accent)',
  '--sn-list-item-focus-border': 'var(--sn-sys-accent)',
  '--sn-list-item-radius': 'calc(4px * var(--sn-theme-radius-scale))',
  '--sn-list-item-gap': '10px',
  '--sn-list-item-min-height': '34px',
  '--sn-list-item-padding': '8px 10px',
  '--sn-list-item-disabled-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-list-item-icon-size': '18px',
  '--sn-list-item-icon-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-list-item-icon-font-size': '16px',
  '--sn-list-item-label-color': 'var(--sn-sys-on-surface)',
  '--sn-list-item-label-size': '12px',
  '--sn-list-item-label-weight': '500',
  '--sn-list-item-description-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-list-item-description-size': '11px',
  '--sn-list-item-meta-max-width': '38%',
  '--sn-list-item-meta-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-list-item-meta-size': '10px',

  '--sn-list-detail-bg': 'var(--sn-sys-surface-panel)',
  '--sn-list-detail-border': 'var(--sn-sys-outline)',
  '--sn-list-detail-radius': 'var(--sn-card-radius)',
  '--sn-list-detail-sidebar-width': 'minmax(220px, 30%)',
  '--sn-list-detail-min-height': '0',
  '--sn-list-detail-height': '100%',
  '--sn-list-detail-color': 'var(--sn-sys-on-surface)',
  '--sn-list-detail-sidebar-bg': 'var(--sn-sys-surface-raised)',
  '--sn-list-detail-main-bg': 'transparent',
  '--sn-list-detail-header-bg': 'transparent',
  '--sn-list-detail-header-gap': '8px',
  '--sn-list-detail-header-min-height': '42px',
  '--sn-list-detail-header-padding': '10px 12px',
  '--sn-list-detail-icon-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-list-detail-icon-size': '18px',
  '--sn-list-detail-main-padding': '12px',
  '--sn-list-detail-list-padding': '8px',
  '--sn-list-detail-empty-padding': '12px',
  '--sn-list-detail-title-size': '12px',
  '--sn-list-detail-title-color': 'var(--sn-sys-on-surface)',
  '--sn-list-detail-title-weight': '600',
  '--sn-list-detail-title-transform': 'uppercase',
  '--sn-list-detail-description-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-list-detail-description-size': '11px',

  '--sn-composer-bg': 'var(--sn-sys-surface-raised)',
  '--sn-composer-border': 'var(--sn-sys-outline)',
  '--sn-composer-action-bg': 'color-mix(in oklch, var(--sn-sys-accent) var(--sn-sys-state-hover-mix), var(--sn-composer-bg))',
  '--sn-composer-radius': 'calc(20px * var(--sn-theme-composer-radius-scale, 1))',
  '--sn-composer-send-size': '32px',
  '--sn-composer-send-icon-size': '18px',
  '--sn-composer-collapsed-control-width': '10px',
  '--sn-composer-collapsed-control-padding': '10px',
  '--sn-composer-control-gap': '8px',
  '--sn-composer-padding': '12px 20px 16px',
  '--sn-composer-body-padding': '8px 8px 8px 16px',
  '--sn-composer-input-min-height': '20px',
  '--sn-composer-input-padding': 'calc(4px * var(--sn-theme-density)) max(0px, calc(var(--sn-composer-radius) * 0.45))',

  '--sn-chat-bg': 'transparent',
  '--sn-chat-gap': '8px',
  '--sn-chat-message-bg': 'var(--sn-sys-surface-raised)',
  '--sn-chat-user-message-bg': 'var(--sn-composer-bg)',
  '--sn-chat-agent-message-bg': 'var(--sn-sys-surface-raised)',
  '--sn-chat-message-radius': '8px',
  '--sn-chat-transcript-padding': '24px 20px 12px',
  '--sn-chat-scroll-bottom': '18px',
  '--sn-chat-item-icon-color': 'currentColor',
  '--sn-chat-item-child-shadow': '2px 0 4px color-mix(in oklab, var(--sn-sys-surface) 70%, transparent)',
  '--sn-chat-live-icon-size': '14px',
  '--sn-chat-meta-icon-size': '12px',
  '--sn-chat-status-icon-size': '12px',
  '--sn-chat-tool-icon-size': '14px',
  '--sn-chat-summary-icon-size': '16px',

  '--sn-output-preview-gap': '8px',
  '--sn-output-preview-padding': '10px',
  '--sn-output-preview-border': 'var(--sn-border)',
  '--sn-output-preview-radius': 'calc(6px * var(--sn-theme-radius-scale))',
  '--sn-output-preview-bg': 'var(--sn-sys-surface-raised)',
  '--sn-output-preview-muted': 'var(--sn-sys-on-surface-dim)',
  '--sn-output-preview-title': 'var(--sn-sys-on-surface)',
  '--sn-output-preview-label': 'var(--sn-sys-on-surface)',
  '--sn-output-preview-canvas-radius': 'calc(5px * var(--sn-theme-radius-scale))',
  '--sn-output-preview-grid': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.04)',
  '--sn-output-preview-item-border': 'var(--sn-border)',
  '--sn-output-preview-item-radius': 'calc(5px * var(--sn-theme-radius-scale))',
  '--sn-output-preview-item-bg': 'var(--sn-sys-surface-raised)',
  '--sn-output-preview-edge-bg': 'color-mix(in oklch, var(--sn-sys-accent) var(--sn-sys-state-hover-mix), var(--sn-output-preview-bg))',

  '--sn-sidebar-width': '220px',
  '--sn-sidebar-collapsed-width': 'var(--sn-layout-header-block-size, calc(var(--sn-layout-header-min-height, 28px) + 3px))',
  '--sn-sidebar-resize-width': '5px',
  '--sn-sidebar-resize-offset': '2px',

  '--sn-source-bg': 'var(--sn-sys-surface)',
  '--sn-source-header-bg': 'var(--sn-node-header-bg)',
  '--sn-source-border': 'var(--sn-sys-outline)',
  '--sn-source-toolbar-gap': '8px',
  '--sn-source-action-bg': 'var(--sn-sys-surface)',
  '--sn-source-action-hover-bg': 'color-mix(in oklch, var(--sn-sys-accent) var(--sn-sys-state-hover-mix), var(--sn-source-action-bg))',
  '--sn-source-action-radius': 'calc(4px * var(--sn-theme-radius-scale))',

  '--sn-source-editor-bg': 'var(--sn-sys-surface)',
  '--sn-editor-bg': 'var(--sn-source-editor-bg)',
  '--sn-source-editor-color': 'var(--sn-sys-on-surface)',
  '--sn-editor-text': 'var(--sn-source-editor-color)',
  '--sn-editor-border': 'var(--sn-sys-outline)',
  '--sn-editor-radius': '0',
  '--sn-editor-font': 'var(--sn-font-mono)',
  '--sn-source-editor-padding': '14px 16px',
  '--sn-source-editor-font-size': '12px',
  '--sn-source-editor-line-height': '1.6',
  '--sn-source-editor-tab-size': '2',
  '--sn-source-editor-placeholder-color': 'var(--sn-sys-on-surface-dim)',

  '--sn-syntax-keyword': 'hsl(var(--sn-hue-danger) var(--sn-sat-vivid) 86.0%)',
  '--sn-syntax-string': 'hsl(var(--sn-hue-warning) var(--sn-sat-vivid) 70.0%)',
  '--sn-syntax-comment': 'var(--sn-sys-on-surface-dim)',
  '--sn-syntax-function': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) 84%)',
  '--sn-syntax-number': 'var(--sn-syntax-string)',
  '--sn-syntax-builtin': 'var(--sn-syntax-function)',
  '--sn-syntax-property': 'hsl(var(--sn-hue-data) var(--sn-sat-vivid) 78%)',
  '--sn-syntax-literal': 'var(--sn-syntax-keyword)',
  '--sn-syntax-doc': 'hsl(var(--sn-hue-success) 22% 56%)',
  '--sn-syntax-doc-tag': 'hsl(var(--sn-hue-success) 50% 70%)',
  '--sn-syntax-doc-type': 'hsl(var(--sn-hue-accent) 72% 72%)',
  '--sn-syntax-template': 'hsl(var(--sn-hue-warning) 44% 64%)',
  '--sn-syntax-template-tag': 'hsl(var(--sn-hue-accent) 48% 58%)',
  '--sn-syntax-template-attr': 'hsl(var(--sn-hue-accent) var(--sn-sat-vivid) 80%)',
  '--sn-syntax-template-bracket': 'var(--sn-sys-on-surface-dim)',
  '--sn-syntax-template-interpolation': 'hsl(var(--sn-hue-warning) 50% 76%)',
  '--sn-syntax-template-selector': 'hsl(var(--sn-hue-warning) 56% 68%)',
  '--sn-syntax-template-property': 'var(--sn-syntax-template-attr)',
  '--sn-syntax-template-value': 'var(--sn-syntax-template)',
  '--sn-diagnostic-error-bg': 'color-mix(in oklab, var(--sn-sys-danger) 7%, transparent)',
  '--sn-diagnostic-error-border': 'color-mix(in oklab, var(--sn-sys-danger) 55%, transparent)',
  '--sn-diagnostic-warning-bg': 'color-mix(in oklab, var(--sn-sys-warning) 5%, transparent)',
  '--sn-diagnostic-warning-border': 'color-mix(in oklab, var(--sn-sys-warning) 45%, transparent)',

  '--sn-loading-overlay-bg': 'var(--sn-sys-surface)',
  '--sn-loading-bg': 'var(--sn-loading-overlay-bg)',
  '--sn-loading-text': 'var(--sn-sys-on-surface-dim)',
  '--sn-loading-accent': 'var(--sn-sys-accent)',
  '--sn-loading-radius': '2px',
  '--sn-loading-overlay-z': '500',
  '--sn-loading-overlay-gap': '16px',
  '--sn-loading-label-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-loading-label-size': '11px',
  '--sn-loading-phase-color': 'var(--sn-sys-accent)',
  '--sn-loading-phase-size': '10px',
  '--sn-loading-track-bg': 'hsl(var(--sn-hue-base) var(--sn-sat-muted) var(--sn-lit-text) / 0.08)',
  '--sn-loading-track-width': '200px',
  '--sn-loading-track-height': '2px',
  '--sn-loading-bar-bg': 'var(--sn-sys-accent)',
  '--sn-loading-bar-shadow': '0 0 8px color-mix(in oklab, var(--sn-sys-accent) 45%, transparent)',
  '--sn-loading-track-radius': '2px',
  '--sn-loading-sub-color': 'var(--sn-sys-on-surface-dim)',
  '--sn-loading-sub-size': '9px',

  '--sn-effect-hover-transition': 'background-color calc(120ms * var(--sn-theme-motion-scale)) ease, border-color calc(120ms * var(--sn-theme-motion-scale)) ease',
  '--sn-effect-focus-ring': '0 0 0 2px hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.35)',
  '--sn-effect-drag-shadow': '0 14px calc(32px * var(--sn-theme-elevation-scale)) hsl(var(--sn-hue-base) var(--sn-sat-muted) 0% / 0.35)',
  '--sn-effect-loading-pulse': 'linear-gradient(90deg, transparent, hsl(var(--sn-hue-accent) var(--sn-sat-vivid) var(--sn-lit-accent) / 0.6), transparent)',

  '--sn-shape-fill': 'var(--sn-sys-surface-raised)',
  '--sn-shape-stroke': 'var(--sn-sys-outline)',
  '--sn-shape-stroke-width': '0.4',
  '--sn-frame-border-width': '2px',
  '--sn-frame-border-style': 'solid',
  '--sn-frame-radius': 'calc(12px * var(--sn-theme-radius-scale))',
  '--sn-frame-font': 'var(--sn-font)',
  '--sn-frame-font-size': '13px',

  '--bg-level-2': 'var(--sn-sys-surface-raised)',
  '--border-color': 'var(--sn-sys-outline)',
  '--text-color': 'var(--sn-sys-on-surface)',
  '--text-color-muted': 'var(--sn-sys-on-surface-dim)',
};

const DEFAULT_DARK_PALETTE_COLORS = {
  '--sn-theme-hue': '218',
  '--sn-theme-chroma': '89%',
  '--sn-theme-bg-lightness': '10%',
  '--sn-theme-surface-lightness': '15.1%',
  '--sn-theme-text-lightness': '98.0%',
  '--sn-theme-density': '1',
  '--sn-theme-radius-scale': '0',
  '--sn-theme-tab-radius-scale': '1',
  '--sn-theme-cell-radius-scale': '1',
  '--sn-theme-composer-radius-scale': '1',
  '--sn-theme-motion-scale': '1',
  '--sn-theme-elevation-scale': '1',
  '--sn-hue-base': '0',
  '--sn-hue-accent': 'var(--sn-theme-hue)',
  '--sn-hue-success': '122',
  '--sn-hue-warning': '36',
  '--sn-hue-danger': '4',
  '--sn-hue-data': '188',
  '--sn-sat': '0%',
  '--sn-sat-vivid': 'var(--sn-theme-chroma)',
  '--sn-sat-muted': '0%',
  '--sn-lit-bg': 'var(--sn-theme-bg-lightness)',
  '--sn-lit-surface': 'var(--sn-theme-surface-lightness)',
  '--sn-lit-hover': '31.2%',
  '--sn-lit-text': 'var(--sn-theme-text-lightness)',
  '--sn-lit-text-dim': '67.6%',
  '--sn-lit-accent': '68.0%',
  '--sn-alpha-overlay': '0.95',
  '--sn-alpha-subtle': '0.15',
  '--sn-alpha-faint': '0.06',
};

/** @type {import('./Theme.js').ThemeDefinition} */
export let DEFAULT_DARK = {
  name: 'default-dark',
  tokens: { ...DEFAULT_DARK_TOKENS },
  extraCSS: themedScrollbarRootStyles,
};

/** @type {import('./Palette.js').PaletteDefinition} */
export let DEFAULT_DARK_PALETTE = {
  name: 'default-dark',
  colors: { ...DEFAULT_DARK_PALETTE_COLORS },
};
